In [2]:
import pandas as pd

df = pd.read_csv('Students_exams.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         1000 non-null   object
 1   math score     1000 non-null   int64
 2   reading score  1000 non-null   int64
 3   writing score  1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [3]:
x =df['math score'].count()
print('count = ' ,x)

1000

In [4]:
x =df['math score'].mean()
print('mean = ' ,x)

mean =  66.089

In [5]:
x =df['math score'].min()
print('min = ' ,x)

min =  0

In [6]:
x =df['math score'].max()
print('max = ' ,x)

max =  100

In [7]:
x =df['math score'].median()
print('median = ' ,x)

median =  66.0

In [8]:
x =df['math score'].quantile(0.5)
print('quantile 50% = ' ,x)

quantile 50% =  66.0

In [9]:
x =df['math score'].quantile(0.25)
print('quantile 25% = ' ,x)

quantile 25% =  57.0

In [10]:
x =df['math score'].quantile(0.75)
print('quantile 75% = ' ,x)

quantile 75% =  77.0

In [13]:
x =df.std(numeric_only =True)
x

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

In [14]:
x =df.mode()
x

   gender  math score  reading score  writing score
0  female          65             72             74