In [1]:
import pandas as pd

df =pd.read_csv("stdMarks.csv")
df.head()

   Id  Math  Phy  Lang Pass
0   1    30   40    80   No
1   2    60   65    45  Yes
2   3    35   40    70   No
3   4    70   75    50  Yes
4   5    80   80    40  Yes

In [4]:
dfcorrel =df[["Math" , "Phy","Lang"]]

correl = dfcorrel.corr(method='pearson')
correl

          Math       Phy      Lang
Math  1.000000  0.970892 -0.328193
Phy   0.970892  1.000000 -0.386725
Lang -0.328193 -0.386725  1.000000