In [1]:
import pandas as pd

In [4]:
df1 =pd.DataFrame({'Column_a':[1, 2 ,3,4] , 'Column_b':['a' , 'b' , 'c' , 'd'],'Column_c':[True , True, False , True]})

In [3]:
df2 =pd.DataFrame({'Column_a': [5,3,7,8] , 'Column_b':['e' , 'f' , 'g' , 'h'],'Column_c':[False , False, True , False]})

In [5]:
df = pd.concat([df1 , df2])
df

   Column_a Column_b  Column_c
0         1        a      True
1         2        b      True
2         3        c     False
3         4        d      True
0         5        e     False
1         3        f     False
2         7        g      True
3         8        h     False

In [6]:
df = pd.concat([df1 , df2] , keys=['df1' , 'df2'])
df

       Column_a Column_b  Column_c
df1 0         1        a      True
    1         2        b      True
    2         3        c     False
    3         4        d      True
df2 0         5        e     False
    1         3        f     False
    2         7        g      True
    3         8        h     False

In [7]:
df = pd.concat([df1 , df2] , ignore_index = True)
df

   Column_a Column_b  Column_c
0         1        a      True
1         2        b      True
2         3        c     False
3         4        d      True
4         5        e     False
5         3        f     False
6         7        g      True
7         8        h     False

In [8]:
df = pd.concat([df1 , df2] , axis = 1)
df

   Column_a Column_b  Column_c  Column_a Column_b  Column_c
0         1        a      True         5        e     False
1         2        b      True         3        f     False
2         3        c     False         7        g      True
3         4        d      True         8        h     False

In [9]:
df_merege = pd.merge(df1 , df2 )
df_merege

Empty DataFrame
Columns: [Column_a, Column_b, Column_c]
Index: []

In [10]:
df_merege = pd.merge(df1 , df2 , on = 'Column_a')
df_merege

   Column_a Column_b_x  Column_c_x Column_b_y  Column_c_y
0         3          c       False          f       False

In [11]:
df2.rename(columns={'Column_a' : 'new_column_a'} ,inplace=True )
df2

   new_column_a Column_b  Column_c
0             5        e     False
1             3        f     False
2             7        g      True
3             8        h     False

In [12]:
df_merage = pd.merge(df1 , df2 , left_on = 'Column_a')

MergeError: Must pass "right_on" OR "right_index".

In [16]:
df_merage = pd.merge(df1 , df2 , left_on = 'Column_a' ,  right_on= 'new_column_a')
df_merage

   Column_a Column_b_x  Column_c_x  new_column_a Column_b_y  Column_c_y
0         3          c       False             3          f       False

In [17]:
df2.rename(columns={'new_column_a' : 'Column_a' } ,inplace=True )
df_merge = pd.merge(df1 , df2 , on = ['Column_a' ,'Column_b'])
df_merge

Empty DataFrame
Columns: [Column_a, Column_b, Column_c_x, Column_c_y]
Index: []